version: "3.9"

services:
  front-end-app:
    container_name: front-end-app
    image: front-end-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8080"
